Updated "chainhooks service with bitcoind" How To doc
hirosystems/chainhook pull request #377
Opened 2023-08-10 16:57 UTC by mefrem

### Description

The ["Run Chainhook as a Service using Bitcoind"](https://docs.hiro.so/chainhook/how-to-guides/how-to-run-chainhook-as-a-service-using-bitcoind) guide was revamped in advance of Chainhooks general launch.

#### Breaking change?

N/A

### Example

N/A

### Checklist

- [ ] All tests pass
- [ ] Tests added in this PR (if applicable)

2023-08-10 17:43 UTC, LakshmiLavanyaKasturi requested changes

2023-08-10 17:43 UTC, LakshmiLavanyaKasturi commented on docs/how-to-guides/how-to-run-chainhook-as-a-service-using-bitcoind.md
> +> While bitcoind can and will start syncing a Bitcoin node, customizing this node to your use cases beyond supporting a Chainhook is out of scope for this guide. See the Bitcoin wiki for [bitcoind](h
Did you mean? https://bitcoin.org/ for bitcoin.org's?

2023-08-10 17:43 UTC, LakshmiLavanyaKasturi commented on docs/how-to-guides/how-to-run-chainhook-as-a-service-using-bitcoind.md
> -The sample payload response should look like this:
Is it intended to remove the sample payload response?

2023-08-10 17:43 UTC, LakshmiLavanyaKasturi commented on docs/how-to-guides/how-to-run-chainhook-as-a-service-using-bitcoind.md
> -  The above command registers the predicates based on the predicate definition in the `ordinals_protocol.json` file.
I think it is important to specify. May I know why we are deleting this?

2023-08-10 17:43 UTC, LakshmiLavanyaKasturi commented on docs/how-to-guides/how-to-run-chainhook-as-a-service-using-bitcoind.md
> -  ```console
How do we start the service if this is removed?

2023-08-11 00:54 UTC, ryanwaits commented
so there's a couple things here that ill create some issues for, but wanted to add here to provide some context since its docs related:

ingesting historical data and triggering actions based on predicates when using Chainhook as a Service:
> there are outstanding questions regarding the behavior of the Chainhook service when dealing with historical data and triggering actions based on registered or scanned predicates

> examples provided in the documentation, including those mentioned here, have not been successful in scanning based on `start_block` and/or `end_block` criteria.

better examples:

> currently, for demonstration purposes, a stacking pool's Bitcoin address is being used to guarantee some data generation. However, Bitcoin related examples are preferred and updates will be made once we resolve current issues around `ordinals_protocol` scope.

2023-08-11 16:19 UTC, LakshmiLavanyaKasturi approved these changes

2023-08-11 16:19 UTC, LakshmiLavanyaKasturi commented on docs/how-to-guides/how-to-run-chainhook-as-a-service-using-bitcoind.md
> +You can run Chainhook as a service to evaluate your `if_this / then_that` predicates against the Bitcoin blockchain, delivering results—either file appendations or HTTP POST requests to a server you
Chainhook can be used as a service to assess your 'if_this / then_that' predicates against the Bitcoin blockchain. This delivers outcomes by appending files or making HTTP POST requests to your chosen server for your application's needs. You can also dynamically register new predicates as the service runs by enabling the predicates registration API.

2023-08-11 16:20 UTC, LakshmiLavanyaKasturi commented
@mefrem @ryanwaits: LGTM, just a few re-wordings that I suggested.

2023-08-14 13:12 UTC, merged