fix: serialize brc-20 data
hirosystems/chainhook pull request #585
Opened 2024-05-13 14:15 UTC by rafaelcr

2024-05-13 19:11 UTC, MicaiahReid approved these changes

2024-05-13 19:13 UTC, MicaiahReid requested changes
@rafaelcr Would you be able to add tests for these new changes on the rust end? 
There are some related tests here: https://github.com/hirosystems/chainhook/blob/5f20a869acbd057d855b9601a4fb1072e75ab4c4/components/chainhook-sdk/src/chainhooks/bitcoin/tests.rs#L151

Let me know if you want to discuss some possible approaches.

2024-05-14 17:25 UTC, lgalabru approved these changes
LGTM!

2024-05-14 17:53 UTC, MicaiahReid commented on components/chainhook-sdk/src/chainhooks/bitcoin/tests.rs
> +    let _: BitcoinChainhookOccurrencePayload = serde_json::from_slice(&payload[..]).unwrap();
```suggestion
    let deserialized: BitcoinChainhookOccurrencePayload =
        serde_json::from_slice(&payload[..]).unwrap();
    assert!(deserialized.apply[0].block.transactions[0]
        .metadata
        .brc20_operation
        .is_some());
```

2024-05-14 18:01 UTC, MicaiahReid approved these changes

2024-05-14 19:36 UTC, merged