chore: upgrade to rust 1.80
hirosystems/chainhook pull request #631
Opened 2024-08-01 21:23 UTC by chenrui333

- bump time crate, seeing build failure in https://github.com/Homebrew/homebrew-core/actions/runs/10126855440/job/28023138251 relates to https://github.com/time-rs/time/issues/693
- also update toolchain and run the cargo fmt/clippy fixes

2024-08-01 21:23 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/hirosystems/chainhook?pullRequest=631) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/hirosystems/chainhook?pullRequest=631) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/hirosystems/chainhook?pullRequest=631) it.</sub>

2024-08-06 16:11 UTC, rafaelcr commented
@chenrui333 thanks for this PR, looks very good so far. I've moved the base branch to `develop`, though, since we'll need to put the change there first. Could you please rebase your branch and fix the conflicts?

2024-08-08 15:13 UTC, rafaelcr requested changes
Please resolve conflicts against develop

2024-08-13 12:17 UTC, chenrui333 commented
just resolve the conflicts (it might be worth making develop the default branch)

2024-09-17 20:31 UTC, merged